import Head from "next/head";
import HomeProducts from "../components/Homepage/HomeProducts";
import { loadUser } from "../redux/actions/userAction.js";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import BasicAlerts from "../components/Alert";

export default function Home({ data }) {
  const { isAuthenticated, user, success, error } = useSelector(
    (state) => state.loadUser
  );
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(loadUser());
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      {error && (
        <BasicAlerts message={error}/>
      )}
      <main className="">
        <HomeProducts products={data.products} />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`${process.env.NEXT_PUBLIC_GITPOD_HOST}/api/products`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
