export const CREATE_PRODUCT_REQ = "CREATE_PRODUCT_REQ";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";


export const ALL_PRODUCT_REQ = "ALL_PRODUCT_REQ";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";